import OpenAI from "openai";

/**
 * Project PHOENIX
 * OpenAI Client Configuration
 *
 * NOTE:
 * This file uses a mock fallback so the application
 * continues to work during development if an API key
 * is not provided.
 */

export const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export const hasOpenAIKey = Boolean(
  process.env.OPENAI_API_KEY
);

/**
 * Generates an AI response.
 */
export async function generateAIResponse(
  prompt: string
): Promise<string> {
  // Mock mode for development/demo
  if (!hasOpenAIKey) {
    const mockResponses: Record<string, string> = {
      "show my passport":
        "Your passport is securely stored in the PHOENIX Vault. Last accessed on July 20, 2026.",

      "find my fee receipt":
        "I found 3 fee receipts. The latest one was uploaded on July 15, 2026.",

      "generate my timeline":
        "Timeline Generated:\n• School Admission (2015)\n• Engineering Admission (2024)\n• Passport Application (2025)\n• Education Loan Approval (2026)",

      "list all uploaded documents":
        "Documents Found:\n1. passport.pdf\n2. aadhaar_card.png\n3. education_loan.pdf\n4. fee_receipt.pdf",

      "recommend a backup strategy":
        "Recommended Strategy:\n• Enable cloud backups.\n• Export monthly reports.\n• Configure emergency contacts.\n• Enable multi-factor authentication.",
    };

    const key = prompt.toLowerCase().trim();

    return (
      mockResponses[key] ??
      "PHOENIX AI is running in mock mode. Connect an OpenAI API key to enable advanced AI capabilities."
    );
  }

  try {
    const response = await openai.responses.create({
      model: "gpt-5.5",
      input: [
        {
          role: "system",
          content:
            "You are PHOENIX AI, an intelligent cybersecurity and digital recovery assistant. Help users manage documents, timelines, and security-related tasks.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
    });

    return (
      response.output_text ??
      "No response generated by PHOENIX AI."
    );
  } catch (error) {
    console.error("OpenAI Error:", error);

    return "Unable to connect to PHOENIX AI services at this time. Please try again later.";
  }
}

/**
 * Checks whether OpenAI is configured.
 */
export function getAIStatus() {
  return {
    connected: hasOpenAIKey,
    mode: hasOpenAIKey ? "live" : "mock",
    model: hasOpenAIKey ? "gpt-5.5" : "mock-engine",
  };
}